### ISSUE TITLE
port sord_validate to PCRE2

### ISSUE THREAD

**Issue by pabs3** [drobilla/sord#6]
[Debian is migrating from PCRE to PCRE2](https://lists.debian.org/msgid-search/25455125-2c65-8881-509c-cfd311a95725@debian.org). This means that the Debian package of sordi [dropped the PCRE dependency](https://bugs.debian.org/1020931), which means that the sordi_validate command is no longer available in Debian. It would be useful for sordi_validate to still exist, which means that the code needs to be ported to the new [PCRE2 API](https://pcre.org/current/doc/html/pcre2api.html). Keeping support for the old PCRE API is probably a good idea but not strictly necessary for Debian.

**Comment by drobilla** [comment]
Someone had sent a patch for this earlier, but unfortunately it didn't quite work.

I figured it out by scouring the Internet a bit.  The documentation is pretty weak about what's required and what's optional.

Ported in 67bcd63

**Comment by pabs3** [comment]
Excellent, thanks for that.

I will get the Debian maintainer to re-add it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
PS: would it be possible to get a new release/tag for this?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by drobilla** [comment]
Nope.  Releases happen when they happen, and people always want one for everything.  Usually, in my experience, only so they can test it after the fact, and file more issues, then demand yet another release for _that_, only so they can then test after the fact, and... ;)

So, I make releases at times that minimize that sort of egregious waste of my time and energy (not to mention release artifact spam).  That means at least a couple of weeks after making a major change like this, because then at least it gets some testing from the people working out of git.

**Comment by pabs3** [comment]
OK, makes sense, I'll inform the Debian maintainer :)

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by drobilla** [comment]
OK, thanks.  They can cherry pick the patch easily enough if they're in a rush.

I have a few things to consider for the next round of stable releases, but probably next week or so.  The next major versions won't use PCRE at all, but that's a while out.

**Comment by snd1** [comment]
Thank you, seems it works fine :) A patched version is just uploaded https://tracker.debian.org/pkg/sord
