### ISSUE TITLE
Any SPARQL Query engines for Sord? 

### ISSUE THREAD

**Issue by gpicciuca** [drobilla/sord#9]
Hello,
Are there any compatible SPARQL Query engines that work with Sord?

**Comment by drobilla** [comment]
Not that I know of and sord is due to be replaced by the next version of serd that incorporates the storage part, which would be a better foundation for that, but is taking forever.

Historical note: I was originally using SPARQL (on redland) for the things I'm using serd/sord for and eventually realized it was worse in every way in that context than dumb code with loops and iteration and such.  That's a specific use case though, it would be nice in general.
